### ISSUE TITLE
NFC don't working properly

### ISSUE THREAD

**Issue by ra1nst0rm3d** [CarbonROM/android_device_sony_sumire#1]
Problem analogically with Z3 stock tree on @sonyxperiadev 
@Myself5, you help me fix this problem?

**Comment by Myself5** [comment]
Neither me nor @sonyxperiadev themselves care about the Z1-Z5 with their trees anymore.

Carbon still supports the Z1-Z3 and NFC is working fine there. Z5 is not supported anymore, thanks to having the worst camera ever.

**Comment by ra1nst0rm3d** [comment]
Camera on Z5 is working fine. What is problem with cam?

**Comment by Myself5** [comment]
Also the trees you commented this on have working NFC. They are stock based, and have nothing to do with the @sonyxperiadev trees.

**Comment by ra1nst0rm3d** [comment]
Z5 don't sending files on my Z1. NFC don't working

**Comment by ra1nst0rm3d** [comment]
Maybe try to change files libnfc* from Z3?
P.S Sorry for my english, i'm from Russia

**Comment by Myself5** [comment]
I doubt that you tested it on the latest CarbonROM release that exists for the Z5. You just opened an issue saying it doesn't work on AOSP. I don't care about AOSP and I don't care about anything on @sonyxperiadev anymore. I've given them a fair share of attempts to prove that their work is near daily driver status, and they kept on disappointing.

The CarbonROM trees have nothing to do with AOSP or @sonyxperiadev. NFC works here.

**Comment by ra1nst0rm3d** [comment]
I built CR from scratch 20th May and NFC there don't working.
Sending files from my Z5 to Z1 on stock ROM don't working

**Comment by ra1nst0rm3d** [comment]
I'm so sorry, AndroidBeam in latest official Carbon is working, but contactless pay don't working

**Comment by Myself5** [comment]
That's probably Safetynet then. Nothing we can do about it. Also please note that the Xperia Z5 is no longer supported for quite a while now.

**Comment by ra1nst0rm3d** [comment]
I'm very sorry((

**Comment by ra1nst0rm3d** [comment]
This is not SafetyNet. I'm fixed it but problem is there

**Comment by Myself5** [comment]
>Please note that the Xperia Z5 is no longer supported for quite a while now.

Only thing you can still try is to check out the recent HCE commits on the Z3/shinano trees.

**Comment by ra1nst0rm3d** [comment]
This commit?
https://github.com/CarbonROM/android_device_sony_z3c/commit/bf7e0159457b41fc14408be722bf61cb9a9178b2

**Comment by Myself5** [comment]
https://github.com/CarbonROM/android_device_sony_z3c/commit/03f0990bf09d7ddc885c231fe09306136e71d396
https://github.com/CarbonROM/android_device_sony_z3c/commit/bf7e0159457b41fc14408be722bf61cb9a9178b2

If these two don't work then you're out of luck.

**Comment by ra1nst0rm3d** [comment]
Thanks for private extended support)

**Comment by ra1nst0rm3d** [comment]
Yes, it worked!
